name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: npm install, build #, and test
        run: |
          npm install
          npm run build --if-present
          #npm test

      - name: Build
        env:
          GO111MODULE: on
        run: make build

      - name: Package
        run: npx grafana-toolkit plugin:ci-package
